### ISSUE TITLE
Add More Tags to the Compiler

### ISSUE THREAD

**Issue by ntrupin** [ntrupin/LineScript#12]
We’re looking for anyone who would like to add to the compiler.

See CONTRIBUTING.md for details.

**Comment by Yamboy1** [comment]
I'm considering making an img tag, my only question is whether it would be intuitive enough to have the href of the element as the `text`

On Aug 26, 2018 8:26 AM, Noah Trupin <notifications@github.com> wrote:

We’re looking for anyone who would like to add to the compiler.

See CONTRIBUTING.md for details.

**Comment by ntrupin** [comment]
Yes, I think it would work well to use the image href as the text, so attributes could be put in the argument sections.

I'm giving you the go, just make sure to update the documentation accordingly!

**Comment by Yamboy1** [comment]
so for example
```
img :: https://example.com/test.jpg

**Comment by ntrupin** [comment]
Perfect! That way, the user could do stuff like

```
img -> width="50%" :: https://example.com/test.jpg
```
