### ISSUE TITLE
Blank lines repeat

### ISSUE THREAD

**Issue by Yamboy1** [ntrupin/LineScript#14]
**Describe the bug**

Any blank lines repeat the line before it.

**To Reproduce**
    1. Add a new line to the end/middle of one of the examples

**Expected behavior**
Nothing should change

**Actual behavior**
The line above it is printed twice

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Browser: Chromium
 - Version: 65

**Comment by ntrupin** [comment]
Part of the LineScript syntax is that there are no blank lines, everything fits together.
