### ISSUE TITLE
Make compiler.js much more consise

### ISSUE THREAD

**Issue by Yamboy1** [ntrupin/LineScript#21]
**Is your feature request related to a problem? Please describe.**
If you look at the code for [compiler.js](https://github.com/ntrupin/LineScript/blob/master/src/compiler.js), you can see there is a lot of overuse of code. `h1,h2,h3,h4,h5,h6,p,a,button,abbr` all use exactly the same code per case, just a change in the tag name.

**Describe the solution you'd like**
I've got an idea in mind to solve this, which is the check for all of the above cases, and have it dynamically add in the tag, removing all of the extra code that is currently being used.

```js
function parse(cv) {
 c = cv.toString().split(" :: ")
 v = c[0].split(" -> ")
 tagName = v[0].replace(/\s/g,'')
 switch(tagName) {
  // Heading 1
  case "h1":
  case "h2":
  case "h3":
  case "h4":
  // This continues on for all the cases
   switch(v[1]) {
    case undefined:
    case null:
     output = `<${tagName}>${c[1]}</${tagName}>
     return output;
     break;
    default:
     output = `<${tagName} ${v[1]}>${c[1]}</${tagName}>`
     return output;
     break;
   }
 // The other cases might still need to be hardcoded in
}
```
This will remove 100+ lines of code.

NOTE: This is just a proposal, and I'll make a proper PR later. (The code above may be faulty, but it gives the idea)

**Comment by ntrupin** [comment]
I never thought of that!

It would greatly speed up compiling time.

Yes it would be great if you would submit a pull request for it. Thanks!

**Comment by ntrupin** [comment]
We would run multiple circuits for tags that comply to different rules.

i.e. heading and paragraphs would go to together, but a different section would be put in for span and div
