### ISSUE TITLE
remove output variable 

### ISSUE THREAD

**Issue by Yamboy1** [ntrupin/LineScript#23]
This might be a bit down to preference, but I think that you should remove the output variable, from compiler.js, and instead, have the parse function return the output value. Considering the fact that you already have a return statement in the code for each case, all this should require on compiler.js, is to change
```js
output = `<${tagname} ${v[1]}>${c[1]}</${tagname}>`
return output;
```
to
```js
return `<${tagname} ${v[1]}>${c[1]}</${tagname}>`
```
and then, in gate.js, rather than saying
```js
parse(ele)
```
you'd have
```js
const output = parse(ele)
```
This is more explicit about what the variables is, and it makes more sense straight away, without having to think about where the output variable came from, and what it is. Plus using global variables in the way that you currently are, is generally frowned upon by most of  the js community.

**Comment by ntrupin** [comment]
I can’t work on it until this after noon, so I’d appreciate it if you’d submit a pull request. If you cannot or do not want to, I’ll gladly work on it later.

**Comment by Yamboy1** [comment]
sure, I can do it

**Comment by Yamboy1** [comment]
what timezone are you in btw

**Comment by ntrupin** [comment]
USA East

**Comment by ntrupin** [comment]
UTC−05:00

**Comment by ntrupin** [comment]
I completed the task.
