### ISSUE TITLE
remove switch test for null/undefined and replace it with a tagged template literal 

### ISSUE THREAD

**Issue by Yamboy1** [ntrupin/LineScript#25]
instead of checking for null/undefined with a switch statement like we are now:
```js
switch(v[1]) {
    case undefined:
    case null:
     return `<${tagname}>${c[1]}</${tagname}>`;
     break;
    default:
     return `<${tagname} ${v[1]}>${c[1]}</${tagname}>`;
     break;
   }
```
we can replace it with a tagged template literal, which will convert any undefineds or nulls into empty strings. It would then be just a single line:
```js
return stripEmpty`<${tagname} ${v[1]}>${c[1]}</${tagname}>`;
```
Note: I have already made this function/tag, and I know that it works

**Comment by Yamboy1** [comment]
more information on tagged templates: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates

**Comment by Yamboy1** [comment]
Im almost finished inplementing this :smiley:

**Comment by ntrupin** [comment]
Thank you.
